heat_template_version: 2013-05-23

description: 'Simple template to deploy Project Clearwater infrastructure on CloudStack based on http://clearwater.readthedocs.org/en/release-65/Manual_Install/'

parameters:
  api_endpoint:
    type: string
    description: Cloudstack API endpoint

  api_key:
    type: string
    description: API key
    
  api_secret:
    type: string
    description: API secret key

  service_offering_id:
    type: string
    description: CloudStack service offering ID

  template_id:
    type: string
    description: CloudStack template ID

  zone_id:
    type: string
    description: CloudStack zone ID

  network_offering_id:
    type: string
    description: CloudStack network offering ID

  gateway:
    type: string
    description: Clearwater network gateway
    default: 10.0.0.1

  netmask:
    type: string
    description: Clearwater network netmask
    default: 255.255.255.0

  vpc_id:
    type: string
    description: CloudStack VPC ID

  acl_id:
    type: string
    description: ACL to be used for the Clearwater network

  dns_zone:
    type: string
    description: Clearwater DNS zone

  dnssec_key:
    type: string
    description: DNS secret key

  public_ssh_key:
    type: string
    description: Public SSH key

resources:
  clearwater_network:
    type: Cloudstack::Network::Network
    properties: 
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-network
      display_text: clearwater_network
      network_offering_id: { get_param: network_offering_id }
      zone_id: { get_param: zone_id }
      gateway: { get_param: gateway }
      netmask: { get_param: netmask }
      vpc_id: { get_param: vpc_id }
      acl_id: { get_param: acl_id }

  ralf:
    type: Cloudstack::Compute::VirtualMachine
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-ralf
      template_id: { get_param: template_id }
      service_offering_id: { get_param: service_offering_id }
      network_ids: [ { get_attr: [ clearwater_network, id ] } ]
      zone_id: { get_param: zone_id }
      user_data:
        str_replace:
          template: { get_file: ../scripts/clearwater-deploy-simple.sh }
          params:
            $local_ip: '$local_ip'
            $public_ip: { get_attr: [ ralf_floating_ip, ipaddress ] }
            $ralf_local_ip: { get_attr: [ ralf_floating_ip, ipaddress ] }
            $homer_local_ip: { get_attr: [ homer_floating_ip, ipaddress ] }
            $ellis_local_ip: { get_attr: [ ellis_floating_ip, ipaddress ] }
            $bono_local_ip: { get_attr: [ bono_floating_ip, ipaddress ] }
            $sprout_local_ip: { get_attr: [ sprout_floating_ip, ipaddress ] }
            $homestead_local_ip: { get_attr: [ homestead_floating_ip, ipaddress ] }
            $zone: { get_param: dns_zone }
            $dnssec_key: { get_param: dnssec_key }
            $dns_ip: { get_attr: [dns_floating_ip, ipaddress] }
            $hostname: 'ralf'
            $public_ssh_key: { get_param: public_ssh_key }

  ralf_floating_ip:
    type: Cloudstack::Network::Address
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      vpc_id: { get_param: vpc_id }

  ralf_nat:
    type: Cloudstack::Network::StaticNAT
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      ip_address_id: { get_attr: [ ralf_floating_ip, id ] }
      virtual_machine_id: { get_attr: [ ralf, id ] }
      network_id: { get_attr: [ clearwater_network, id ] }

  homer:
    type: Cloudstack::Compute::VirtualMachine
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-homer
      template_id: { get_param: template_id }
      service_offering_id: { get_param: service_offering_id }
      network_ids: [ { get_attr: [ clearwater_network, id ] } ]
      zone_id: { get_param: zone_id }
      user_data:
        str_replace:
          template: { get_file: ../scripts/clearwater-deploy-simple.sh }
          params:
            $local_ip: '$local_ip'
            $public_ip: { get_attr: [ homer_floating_ip, ipaddress ] }
            $ralf_local_ip: { get_attr: [ ralf_floating_ip, ipaddress ] }
            $homer_local_ip: { get_attr: [ homer_floating_ip, ipaddress ] }
            $ellis_local_ip: { get_attr: [ ellis_floating_ip, ipaddress ] }
            $bono_local_ip: { get_attr: [ bono_floating_ip, ipaddress ] }
            $sprout_local_ip: { get_attr: [ sprout_floating_ip, ipaddress ] }
            $homestead_local_ip: { get_attr: [ homestead_floating_ip, ipaddress ] }
            $zone: { get_param: dns_zone }
            $dnssec_key: { get_param: dnssec_key }
            $dns_ip: { get_attr: [dns_floating_ip, ipaddress] }
            $hostname: 'homer'
            $public_ssh_key: { get_param: public_ssh_key }

  homer_floating_ip:
    type: Cloudstack::Network::Address
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      vpc_id: { get_param: vpc_id }
 
  homer_nat:
    type: Cloudstack::Network::StaticNAT
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      ip_address_id: { get_attr: [ homer_floating_ip, id ] }
      virtual_machine_id: { get_attr: [ homer, id ] }
      network_id: { get_attr: [ clearwater_network, id ] }

  ellis:
    type: Cloudstack::Compute::VirtualMachine
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-ellis
      template_id: { get_param: template_id }
      service_offering_id: { get_param: service_offering_id }
      network_ids: [ { get_attr: [ clearwater_network, id ] } ]
      zone_id: { get_param: zone_id }
      user_data:
        str_replace:
          template: { get_file: ../scripts/clearwater-deploy-simple.sh }
          params:
            $local_ip: '$local_ip'
            $public_ip: { get_attr: [ ellis_floating_ip, ipaddress ] }
            $ralf_local_ip: { get_attr: [ ralf_floating_ip, ipaddress ] }
            $homer_local_ip: { get_attr: [ homer_floating_ip, ipaddress ] }
            $ellis_local_ip: { get_attr: [ ellis_floating_ip, ipaddress ] }
            $bono_local_ip: { get_attr: [ bono_floating_ip, ipaddress ] }
            $sprout_local_ip: { get_attr: [ sprout_floating_ip, ipaddress ] }
            $homestead_local_ip: { get_attr: [ homestead_floating_ip, ipaddress ] }
            $zone: { get_param: dns_zone }
            $dnssec_key: { get_param: dnssec_key }
            $dns_ip: { get_attr: [dns_floating_ip, ipaddress] }
            $hostname: 'ellis'
            $public_ssh_key: { get_param: public_ssh_key }

  ellis_floating_ip:
    type: Cloudstack::Network::Address
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      vpc_id: { get_param: vpc_id }

  ellis_nat:
    type: Cloudstack::Network::StaticNAT
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      ip_address_id: { get_attr: [ ellis_floating_ip, id ] }
      virtual_machine_id: { get_attr: [ ellis, id ] }
      network_id: { get_attr: [ clearwater_network, id ] }

  bono:
    type: Cloudstack::Compute::VirtualMachine
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-bono
      template_id: { get_param: template_id }
      service_offering_id: { get_param: service_offering_id }
      network_ids: [ { get_attr: [ clearwater_network, id ] } ]
      zone_id: { get_param: zone_id }
      user_data:
        str_replace:
          template: { get_file: ../scripts/clearwater-deploy-simple.sh }
          params:
            $local_ip: '$local_ip'
            $public_ip: { get_attr: [ bono_floating_ip, ipaddress ] }
            $ralf_local_ip: { get_attr: [ ralf_floating_ip, ipaddress ] }
            $homer_local_ip: { get_attr: [ homer_floating_ip, ipaddress ] }
            $ellis_local_ip: { get_attr: [ ellis_floating_ip, ipaddress ] }
            $bono_local_ip: { get_attr: [ bono_floating_ip, ipaddress ] }
            $sprout_local_ip: { get_attr: [ sprout_floating_ip, ipaddress ] }
            $homestead_local_ip: { get_attr: [ homestead_floating_ip, ipaddress ] }
            $zone: { get_param: dns_zone }
            $dnssec_key: { get_param: dnssec_key }
            $dns_ip: { get_attr: [dns_floating_ip, ipaddress] }
            $hostname: 'bono'
            $public_ssh_key: { get_param: public_ssh_key }

  bono_floating_ip:
    type: Cloudstack::Network::Address
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      vpc_id: { get_param: vpc_id }
 
  bono_nat:
    type: Cloudstack::Network::StaticNAT
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      ip_address_id: { get_attr: [ bono_floating_ip, id ] }
      virtual_machine_id: { get_attr: [ bono, id ] }
      network_id: { get_attr: [ clearwater_network, id ] }

  sprout:
    type: Cloudstack::Compute::VirtualMachine
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-sprout
      template_id: { get_param: template_id }
      service_offering_id: { get_param: service_offering_id }
      network_ids: [ { get_attr: [ clearwater_network, id ] } ]
      zone_id: { get_param: zone_id }
      user_data:
        str_replace:
          template: { get_file: ../scripts/clearwater-deploy-simple.sh }
          params:
            $local_ip: '$local_ip'
            $public_ip: { get_attr: [ sprout_floating_ip, ipaddress ] }
            $ralf_local_ip: { get_attr: [ ralf_floating_ip, ipaddress ] }
            $homer_local_ip: { get_attr: [ homer_floating_ip, ipaddress ] }
            $ellis_local_ip: { get_attr: [ ellis_floating_ip, ipaddress ] }
            $bono_local_ip: { get_attr: [ bono_floating_ip, ipaddress ] }
            $sprout_local_ip: { get_attr: [ sprout_floating_ip, ipaddress ] }
            $homestead_local_ip: { get_attr: [ homestead_floating_ip, ipaddress ] }
            $zone: { get_param: dns_zone }
            $dnssec_key: { get_param: dnssec_key }
            $dns_ip: { get_attr: [dns_floating_ip, ipaddress] }
            $hostname: 'sprout'
            $public_ssh_key: { get_param: public_ssh_key }

  sprout_floating_ip:
    type: Cloudstack::Network::Address
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      vpc_id: { get_param: vpc_id }
 
  sprout_nat:
    type: Cloudstack::Network::StaticNAT
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      ip_address_id: { get_attr: [ sprout_floating_ip, id ] }
      virtual_machine_id: { get_attr: [ sprout, id ] }
      network_id: { get_attr: [ clearwater_network, id ] }

  homestead:
    type: Cloudstack::Compute::VirtualMachine
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-homestead
      template_id: { get_param: template_id }
      service_offering_id: { get_param: service_offering_id }
      network_ids: [ { get_attr: [ clearwater_network, id ] } ]
      zone_id: { get_param: zone_id }
      user_data:
        str_replace:
          template: { get_file: ../scripts/clearwater-deploy-simple.sh }
          params:
            $local_ip: '$local_ip'
            $public_ip: { get_attr: [ homestead_floating_ip, ipaddress ] }
            $ralf_local_ip: { get_attr: [ ralf_floating_ip, ipaddress ] }
            $homer_local_ip: { get_attr: [ homer_floating_ip, ipaddress ] }
            $ellis_local_ip: { get_attr: [ ellis_floating_ip, ipaddress ] }
            $bono_local_ip: { get_attr: [ bono_floating_ip, ipaddress ] }
            $sprout_local_ip: { get_attr: [ sprout_floating_ip, ipaddress ] }
            $homestead_local_ip: { get_attr: [ homestead_floating_ip, ipaddress ] }
            $zone: { get_param: dns_zone }
            $dnssec_key: { get_param: dnssec_key }
            $dns_ip: { get_attr: [dns_floating_ip, ipaddress] }
            $hostname: 'homestead'
            $public_ssh_key: { get_param: public_ssh_key }

  homestead_floating_ip:
    type: Cloudstack::Network::Address
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      vpc_id: { get_param: vpc_id }

  homestead_nat:
    type: Cloudstack::Network::StaticNAT
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      ip_address_id: { get_attr: [ homestead_floating_ip, id ] }
      virtual_machine_id: { get_attr: [ homestead, id ] }
      network_id: { get_attr: [ clearwater_network, id ] }

  dns_server:
    type: Cloudstack::Compute::VirtualMachine
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      name: clearwater-dns
      template_id: { get_param: template_id }
      service_offering_id: { get_param: service_offering_id }
      network_ids: [ { get_attr: [ clearwater_network, id ] } ]
      zone_id: { get_param: zone_id }
      user_data:
        str_replace:
          template: { get_file: ../scripts/clearwater-dns.sh }
          params:
            $zone: { get_param: dns_zone }
            $dnssec_key: { get_param: dnssec_key }
            $public_ip: { get_attr: [ dns_floating_ip, ipaddress ] }
            $public_ssh_key: { get_param: public_ssh_key }

  dns_floating_ip:
    type: Cloudstack::Network::Address
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      vpc_id: { get_param: vpc_id }

  dns_nat:
    type: Cloudstack::Network::StaticNAT
    properties:
      api_endpoint: { get_param: api_endpoint }
      api_key: { get_param: api_key }
      api_secret: { get_param: api_secret }
      ip_address_id: { get_attr: [ dns_floating_ip, id ] }
      virtual_machine_id: { get_attr: [ dns_server, id ] }
      network_id: { get_attr: [ clearwater_network, id ] }

outputs:
  ralf_external_ip:
    description: Instance external IP address
    value: { get_attr: [ ralf_floating_ip, ipaddress ] }
  ralf_private_ip:
    description: Instance internal IP address
    value: { get_attr: [ ralf, network_ip ] }
  ellis_external_ip:
    description: Instance external IP address
    value: { get_attr: [ ellis_floating_ip, ipaddress ] }
  ellis_private_ip:
    description: Instance internal IP address
    value: { get_attr: [ ellis, network_ip ] }
  homer_external_ip:
    description: Instance external IP address
    value: { get_attr: [ homer_floating_ip, ipaddress ] }
  homer_private_ip:
    description: Instance internal IP address
    value: { get_attr: [ homer, network_ip ] }
  sprout_external_ip:
    description: Instance external IP address
    value: { get_attr: [ sprout_floating_ip, ipaddress ] }
  sprout_private_ip:
    description: Instance internal IP address
    value: { get_attr: [ sprout, network_ip] }
  homestead_external_ip:
    description: Instance external IP address
    value: { get_attr: [ homestead_floating_ip, ipaddress ] }
  homestead_private_ip:
    description: Instance internal IP address
    value: { get_attr: [ homestead, network_ip ] }
  bono_external_ip:
    description: Instance external IP address
    value: { get_attr: [ bono_floating_ip, ipaddress ] }
  bono_private_ip:
    description: Instance internal IP address
    value: { get_attr: [ bono, network_ip ] }
  dns_external_ip:
    description: Instance external IP address
    value: { get_attr: [ dns_floating_ip, ipaddress ] }
  dns_private_ip:
    description: Instance internal IP address
    value: { get_attr: [ dns_server, network_ip ] }
